export type Dish = {
  dish_name: string;
  dish_description: string;
  ingredients: string[];
  recipe: string[];
  image_key: string;
  youtube_link: string[];
  created_at: string;
};

export const dishes: Dish[] = [
  {
    dish_name: "Masala Dosa",
    dish_description:
      "Masala Dosa is a popular South Indian breakfast dish. It is a crispy and savory crepe made from fermented rice and lentil batter, filled with a spicy and savory mixture of mashed potatoes.",
    ingredients: [
      "1 cup rice",
      "1/4 cup urad dal (split black lentils)",
      "2 tablespoons chana dal",
      "1 tablespoon fenugreek seeds",
      "Salt to taste",
      "Oil for cooking",
      "2 large potatoes, boiled and mashed",
      "1 onion, finely chopped",
      "2 green chilies, finely chopped",
      "1 teaspoon mustard seeds",
      "1 teaspoon turmeric powder",
      "Curry leaves",
      "2 tablespoons coriander, finely chopped",
      "Salt to taste",
      "Water as needed",
    ],
    recipe: [
      "Wash and soak the rice, urad dal, chana dal, and fenugreek seeds in water for 5-6 hours.",
      "Drain the water and grind the mixture to a fine paste, adding water as needed to achieve a batter consistency.",
      "Ferment the batter overnight or for 8-10 hours in a warm place.",
      "After fermentation, add salt to the batter and mix well.",
      "Heat a non-stick pan and grease it lightly with oil.",
      "Pour a ladleful of batter onto the pan and spread it evenly to form a thin circle.",
      "Drizzle oil around the edges and cook until the dosa turns golden and crisp.",
      "For the filling: Heat oil in a pan, add mustard seeds, and let them splutter.",
      "Add chopped onions, green chilies, and curry leaves. Sauté until the onions turn translucent.",
      "Add turmeric powder and salt, followed by the mashed potatoes. Mix well.",
      "Add chopped coriander and remove from heat.",
      "Place some of the potato filling in the center of the cooked dosa and fold it.",
      "Serve hot with coconut chutney and sambar.",
    ],
    image_key: "dish/Masala_Dosa.png",
    youtube_link: [
      "J75VQSxOtdo",
      "sX5pYdNbmgo",
      "UiS8UBEe8FI",
      "CCab5oh0ZOc",
      "XgGH3K4agNY",
    ],
    created_at: "2024-09-27T09:55:51.237000",
  },
  {
    dish_name: "Punjabi Chole",
    dish_description:
      "Punjabi Chole is a flavorful and hearty North Indian dish made from chickpeas cooked in a spicy tomato-based sauce, seasoned with traditional Indian spices. It's a popular vegetarian dish often served with rice or flatbreads.",
    ingredients: [
      "2 cups chickpeas, soaked overnight and boiled",
      "2 large onions, finely chopped",
      "2 tomatoes, pureed",
      "1 green chili, chopped",
      "4 cloves of garlic, minced",
      "1 inch ginger, minced",
      "2 tablespoons oil",
      "1 teaspoon cumin seeds",
      "1 bay leaf",
      "1 teaspoon turmeric powder",
      "1 teaspoon coriander powder",
      "1 teaspoon cumin powder",
      "1 teaspoon red chili powder",
      "1 teaspoon garam masala",
      "Salt to taste",
      "Fresh cilantro, chopped for garnish",
      "1 tablespoon lemon juice",
      "2 teaspoons amchur powder (dry mango powder)",
    ],
    recipe: [
      "Heat oil in a large pot over medium heat. Add cumin seeds and bay leaf. Let them sizzle for a few seconds.",
      "Add chopped onions and sauté until they turn golden brown.",
      "Add minced ginger, garlic, and chopped green chili. Cook for an additional 2-3 minutes until the raw aroma disappears.",
      "Stir in tomato puree and cook until oil starts to separate from the sides of the mixture.",
      "Add turmeric powder, coriander powder, cumin powder, red chili powder, and salt. Mix well and cook for 2 minutes.",
      "Add boiled chickpeas along with 1 cup of water and mix well. Cover and simmer for 20 minutes.",
      "Stir in garam masala, amchur powder, and lemon juice. Cook for another 5 minutes to blend the flavors.",
      "Garnish with freshly chopped cilantro before serving.",
      "Serve hot with rice or any flatbread like roti or naan.",
    ],
    image_key:
      'https://eventcrm.io.s3.async () => {\n    if (runtimeConfig.region === void 0) {\n      throw new Error("Region is missing from runtimeConfig");\n    }\n    const region = runtimeConfig.region;\n    if (typeof region === "string") {\n      return region;\n    }\n    return region();\n  }.amazonaws.com/dish/Punjabi_Chole.png',
    youtube_link: [
      "M-ohmJswy6A",
      "4JvLwNUO8zE",
      "lcX_nBvCF7E",
      "wKHdBZuDpOk",
      "UJCzkpCqSGI",
    ],
    created_at: "2024-09-04T05:34:03.392000",
  },
  {
    dish_name: "Kung Pao Cauliflower",
    dish_description:
      "Kung Pao Cauliflower is a delicious, spicy vegetarian version of the classic Chinese stir-fry dish, Kung Pao Chicken. Roasted cauliflower is tossed with bell peppers, peanuts, and a sizzling sauce that features a bold blend of savory, spicy, and slightly sweet flavors.",
    ingredients: [
      "1 medium cauliflower, cut into bite-sized florets",
      "2 tablespoons vegetable oil",
      "1 red bell pepper, diced",
      "1 green bell pepper, diced",
      "2 cloves garlic, minced",
      "1 teaspoon ginger, minced",
      "3 tablespoons soy sauce",
      "2 tablespoons vinegar",
      "1 tablespoon hoisin sauce",
      "2 teaspoons chili paste",
      "1 teaspoon sugar",
      "1/2 cup roasted peanuts",
      "1 spring onion, chopped",
      "Salt to taste",
    ],
    recipe: [
      "Preheat oven to 425°F (220°C). Toss the cauliflower florets with 1 tablespoon of oil and a pinch of salt. Spread the florets on a baking sheet and roast for 20-25 minutes until golden and tender.",
      "While the cauliflower roasts, heat the remaining oil in a large pan over medium heat. Add the red and green bell peppers, and stir-fry for about 5 minutes.",
      "Add the minced garlic and ginger to the pan and sauté for another 2 minutes.",
      "Whisk together soy sauce, vinegar, hoisin sauce, chili paste, and sugar in a small bowl. Pour this mixture into the pan, and bring to a simmer.",
      "Add the roasted cauliflower and peanuts to the pan. Toss everything together to coat the cauliflower and peppers with the sauce. Cook for an additional 2-3 minutes.",
      "Remove from heat and garnish with chopped spring onions. Serve hot.",
    ],
    image_key: "dish/Kung_Pao_Cauliflower.png",
    youtube_link: [
      "YLHCcyEpMP0",
      "qObMNxJMyfw",
      "bPy6OWQyPyA",
      "Jz0t2SO5tsQ",
      "YpfGrC37JFQ",
    ],
    created_at: "2024-09-04T05:36:59.182000",
  },
  {
    dish_name: "Rajasthani Gatte Ki Sabzi",
    dish_description:
      "A traditional Rajasthani vegetarian dish featuring spicy and tangy gram flour dumplings cooked in a spicy yogurt-based curry.",
    ingredients: [
      "1 cup gram flour (besan)",
      "1/4 cup yogurt",
      "1 tsp red chili powder",
      "1/2 tsp turmeric powder",
      "1 tsp coriander powder",
      "1/2 tsp cumin seeds",
      "1/2 tsp fennel seeds",
      "Pinch of asafoetida",
      "2 tbsp oil",
      "Salt to taste",
      "Water as needed",
      "For the gravy:",
      "1 cup yogurt",
      "2 tbsp gram flour (besan)",
      "2 tbsp oil",
      "1 tsp cumin seeds",
      "1/4 tsp mustard seeds",
      "1/2 tsp turmeric powder",
      "1 tsp red chili powder",
      "1/2 tsp garam masala",
      "1 tsp dried fenugreek leaves (kasuri methi)",
      "Salt to taste",
      "2 cups water",
      "Fresh coriander for garnishing",
    ],
    recipe: [
      "Begin by making the gatte: mix gram flour, 1/4 cup yogurt, red chili powder, turmeric powder, coriander powder, cumin seeds, fennel seeds, asafoetida, salt, and 1 tbsp oil in a bowl. Add water gradually to knead into a firm dough.",
      "Divide the dough into equal portions and roll each into a cylindrical shape. Boil water in a large pot and cook these rolled dough pieces for about 10 minutes. Drain and let them cool, then cut into small pieces.",
      "Next, prepare the gravy: in a bowl, whisk 1 cup yogurt with 2 tbsp gram flour until smooth.",
      "Heat 2 tbsp oil in a pan. Add cumin seeds and mustard seeds. Once they crackle, add turmeric powder, red chili powder, salt, and the yogurt-gram flour mixture. Cook on low heat, stirring continuously to prevent curdling.",
      "Add 2 cups of water to the pan and bring the gravy to a boil. Add garam masala, kasuri methi, and the cooked gatte pieces. Let it simmer for 10-15 minutes until the gravy thickens.",
      "Garnish with fresh coriander before serving.",
      "Serve the Gatte Ki Sabzi hot with steamed rice or chapati for a wholesome Rajasthani dinner feast.",
    ],
    image_key: "dish/Rajasthani_Gatte_Ki_Sabzi.png",
    youtube_link: [
      "mVwjjnwAIXY",
      "4_rBh5AomG0",
      "UweArdufFuU",
      "E-AqIiHFL48",
      "lbNnFX5WvL4",
    ],
    created_at: "2024-09-26T04:09:08.347000",
  },
  {
    dish_name: "Sweet Puda",
    dish_description:
      "Sweet Puda, also known as Meetha Puda or Gujarati Pudla, is a delicious sweet pancake originating from Gujarati cuisine. It's commonly enjoyed as a breakfast dish and is made from a batter of wheat flour sweetened with jaggery, spiced subtly with cardamom, and garnished with nutritious additives like sesame seeds and coconut.",
    ingredients: [
      "1 cup whole wheat flour",
      "1/2 cup jaggery (grated)",
      "1/4 cup grated coconut",
      "2 tbsp sesame seeds",
      "1/2 tsp cardamom powder",
      "A pinch of salt",
      "Water as required",
      "Ghee or oil for cooking",
    ],
    recipe: [
      "In a large mixing bowl, combine the whole wheat flour and a pinch of salt.",
      "Add grated jaggery to the bowl and mix well.",
      "Slowly add water to the mixture while continuously stirring to form a smooth batter of pouring consistency.",
      "Mix in the cardamom powder, grated coconut, and sesame seeds into the batter.",
      "Let the batter rest for 10-15 minutes to allow the flavors to meld together.",
      "Heat a non-stick skillet over medium heat and grease it lightly with ghee or oil.",
      "Pour a ladleful of batter onto the skillet and spread it gently to form a round pancake.",
      "Cook the puda on medium heat until the bottom side is golden brown, then flip it and cook the other side.",
      "Repeat the process with the remaining batter.",
      "Serve the sweet pudas hot, optionally accompanied by more grated coconut or a dollop of butter.",
    ],
    image_key: "dish/Sweet_Puda.png",
    youtube_link: [
      "6pZdN-fQ7BQ",
      "62UpRdvnsUc",
      "l4Qxt51Uvk4",
      "3Z5FkxzPvvs",
      "JKQY-Lo4XNE",
    ],
    created_at: "2024-09-04T05:08:29.574000",
  },
  {
    dish_name: "Spicy Szechuan Tofu",
    dish_description:
      "A fiery and flavorful traditional Chinese dish featuring crispy tofu stir-fried in a spicy Szechuan sauce with vegetables.",
    ingredients: [
      "400g firm tofu, pressed and cubed",
      "2 tablespoons vegetable oil",
      "1 red bell pepper, sliced",
      "1 green bell pepper, sliced",
      "3 cloves garlic, minced",
      "1 tablespoon ginger, finely chopped",
      "4 green onions, chopped",
      "1 tablespoon Szechuan peppercorns",
      "2 tablespoons soy sauce",
      "1 tablespoon chili paste",
      "1 teaspoon sugar",
      "Salt to taste",
    ],
    recipe: [
      "Heat the vegetable oil in a large pan over medium heat.",
      "Add the Szechuan peppercorns and stir until fragrant, about 1 minute.",
      "Add the minced garlic and ginger, sauté for 2 minutes until golden.",
      "Increase the heat to high and add the tofu cubes. Stir-fry until they are golden brown, approximately 5 minutes.",
      "Add the red and green bell peppers and stir-fry for another 3 minutes.",
      "Mix soy sauce, chili paste, sugar, and a pinch of salt in a small bowl to make the sauce.",
      "Pour the sauce over the stir-fried tofu and vegetables. Mix well to ensure everything is coated evenly.",
      "Cook for another 2 minutes, allowing the flavors to meld together.",
      "Garnish with green onions before serving.",
    ],
    image_key: "dish/Spicy_Szechuan_Tofu.png",
    youtube_link: [
      "2VwK220z8Tc",
      "KpnLLhBVIjk",
      "ctFEPrR-954",
      "ZfsZwwrTFD4",
      "jCyzcDODL0I",
    ],
    created_at: "2024-09-04T04:55:43.341000",
  },
  {
    dish_name: "Pyaaz Ki Kachori",
    dish_description:
      "Pyaaz ki kachori is a popular spicy breakfast snack from Rajasthan, featuring a pastry filled with a rich and spicy onion mixture.",
    ingredients: [
      "2 cups all-purpose flour",
      "4 tbsp melted ghee",
      "Salt to taste",
      "Water as needed",
      "2 large onions, finely chopped",
      "1 tbsp ginger paste",
      "2 green chilies, finely chopped",
      "1 tsp fennel seeds",
      "1 tsp cumin seeds",
      "1/2 tsp asafoetida",
      "1 tsp garam masala",
      "1 tsp coriander powder",
      "1/2 tsp turmeric powder",
      "1 tsp red chili powder",
      "2 tbsp coriander leaves, chopped",
      "4 tbsp oil",
      "Oil for deep frying",
    ],
    recipe: [
      "To prepare the dough, mix flour, melted ghee, and salt in a bowl. Add water gradually and knead to form a stiff dough. Cover and let it rest for 30 minutes.",
      "Heat oil in a pan. Add cumin seeds, fennel seeds, and asafoetida. Once they start to crackle, add chopped onions, ginger paste, and green chilies. Sauté until onions turn golden brown.",
      "Add coriander powder, turmeric powder, red chili powder, garam masala, and salt to the onion mixture. Cook for 5 minutes on medium heat, stirring continuously.",
      "Turn off the heat and add chopped coriander leaves. Allow the mixture to cool.",
      "Divide the rested dough into equal portions. Roll each portion into a small circle, place a portion of the onion filling in the center, and gather the edges to seal it, forming a ball.",
      "Carefully flatten the stuffed ball using your hands or a rolling pin, ensuring the filling does not come out.",
      "Heat oil in a deep frying pan over medium heat. Deep fry each kachori until golden brown on both sides.",
      "Drain excess oil using paper towels and serve hot with mint or tamarind chutney.",
    ],
    image_key: "dish/Pyaaz_Ki_Kachori.png",
    youtube_link: [
      "5AAC5IHy72U",
      "OnU2I8uO1mQ",
      "MeVJC5iP_nU",
      "urY8nTA_aoQ",
      "PBqK0kEx4-c",
    ],
    created_at: "2024-10-16T08:00:20.620000",
  },
  {
    dish_name: "Dal Baati Churma",
    dish_description:
      "A traditional and quintessential Rajasthani meal combining spiced lentil soup with baked wheat rolls and sweet crumbled dessert.",
    ingredients: [
      "For Baati: 2 cups whole wheat flour, 1/4 cup semolina, 1/2 cup ghee, 1/2 tsp salt, Water as needed",
      "For Dal: 1 cup mixed lentils (toor, moong, masoor), 1/2 tsp turmeric, 1 tsp cumin, 1 tsp mustard seeds, Asafoetida (a pinch), 2 dried red chilies, 1/2 tsp garam masala, Salt to taste, 3 tbsp ghee, 1 onion chopped, 1 tomato chopped, 1 tsp ginger-garlic paste",
      "For Churma: 1 cup coarse wheat flour, 1/4 cup ghee, 1/2 cup powdered sugar, 2 tbsp chopped almonds, 1/2 tsp cardamom powder",
    ],
    recipe: [
      "Baati: Mix whole wheat flour, semolina, salt, and half the ghee. Add water and knead into a stiff dough. Divide into small balls and press slightly. Bake in a preheated oven at 180°C for 25-30 minutes or until cooked.",
      "Dal: Pressure cook the lentils with turmeric and salt. Heat ghee in a pan, add mustard seeds, cumin, asafoetida, and red chilies. Once they crackle, add onions and sauté until golden. Add tomatoes, ginger-garlic paste and cook until oil separates. Add cooked lentils, water for consistency, and garam masala. Simmer for 15 minutes.",
      "Churma: Roll the coarse wheat flour into thick rotis, cook on a griddle until done. Break into pieces and grind into a coarse powder. Heat ghee, add the coarse powder, and roast until aromatic. Cool slightly, add powdered sugar, almonds, and cardamom powder.",
      "Serve hot baatis dipped in ghee with spicy dal and sweet churma on the side.",
    ],
    image_key: "dish/Dal_Baati_Churma.png",
    youtube_link: [
      "kRjU6rZ0ni4",
      "mZ4xTelTAGk",
      "2YIM5-4XIHQ",
      "eWAcCvqIP48",
      "N3_R51ZXn7g",
    ],
    created_at: "2024-10-17T11:12:18.757000",
  },
  {
    dish_name: "Spicy Spinach Pakoras",
    dish_description:
      "Spicy Spinach Pakoras are a delightful, crisp snack made from fresh spinach leaves dipped in a spicy chickpea flour batter and deep-fried until golden brown. These vegetarian treats are perfect for a spicy snack.",
    ingredients: [
      "2 cups fresh spinach leaves",
      "1 cup chickpea flour (besan)",
      "2 tsp red chili powder",
      "1 tsp turmeric powder",
      "1 tsp carom seeds (ajwain)",
      "1 tsp salt",
      "1/2 tsp asafoetida (hing)",
      "1 tbsp ginger-garlic paste",
      "2 green chilies, finely chopped",
      "Water as needed for batter",
      "Oil for deep frying",
    ],
    recipe: [
      "Thoroughly wash the spinach leaves and pat them dry.",
      "In a mixing bowl, combine chickpea flour, red chili powder, turmeric powder, carom seeds, salt, asafoetida, ginger-garlic paste, and chopped green chilies. Mix well.",
      "Gradually add water to the mixture to form a smooth batter that is not too thick or too watery.",
      "Heat oil in a deep frying pan over medium heat.",
      "Dip each spinach leaf in the batter, making sure it is well coated on both sides.",
      "Carefully place the coated spinach leaves in the hot oil and fry until they turn golden brown and crispy.",
      "Remove the pakoras from the oil and place them on paper towels to absorb excess oil.",
      "Serve the Spicy Spinach Pakoras hot with your favorite chutney or sauce.",
    ],
    image_key: "dish/Spicy_Spinach_Pakoras.png",
    youtube_link: [
      "Y1U7XY5cE6s",
      "8bySL76S4_U",
      "sh-KXpnCMAc",
      "_c7WcO7Lwz0",
      "qDMk0K8O6GQ",
    ],
    created_at: "2024-10-17T08:53:54.507000",
  },
  {
    dish_name: "Spicy Fafda Bruschetta",
    dish_description:
      "A delightful fusion of Gujarati and Italian cuisines, blending the spicy zest of Fafda with the classic Italian bruschetta, topped with a spicy tomato salsa.",
    ingredients: [
      "200 grams Fafda",
      "2 medium tomatoes, finely chopped",
      "1 small onion, finely chopped",
      "2 cloves of garlic, minced",
      "1 green chili, finely chopped",
      "10 basil leaves, chopped",
      "2 tablespoons olive oil",
      "Salt to taste",
      "1 teaspoon red chili flakes",
      "1 teaspoon sugar (optional for balancing)",
      "1 tablespoon lemon juice",
    ],
    recipe: [
      "Prepare the spicy tomato salsa by mixing chopped tomatoes, onion, green chili, garlic, basil, salt, red chili flakes, sugar, and lemon juice in a bowl.",
      "Let the salsa sit for 10-15 minutes to blend the flavors together.",
      "Lightly toast the Fafda in a pan with a little olive oil until they are slightly crispy, allowing them to cool slightly after toasting.",
      "Top each piece of toasted Fafda with a generous spoonful of the spicy tomato salsa.",
      "Drizzle olive oil over the topped Fafda bruschetta before serving.",
    ],
    image_key: "dish/Spicy_Fafda_Bruschetta.png",
    youtube_link: [
      "Q0w53qW0fMA",
      "8-JkEaqgrrg",
      "Oy8fucNxEwo",
      "pOSu6PEYRto",
      "oPj1YdlAZn8",
    ],
    created_at: "2024-10-17T08:58:01.994000",
  },
  {
    dish_name: "Sweet and Sour Tofu",
    dish_description:
      "A delightful vegetarian Chinese dish featuring crispy tofu in a vibrant sweet and sour sauce, served with a side of steamed Jasmine rice.",
    ingredients: [
      "200g firm tofu, pressed and cubed",
      "1 tbsp cornstarch",
      "2 tbsp vegetable oil",
      "1 red bell pepper, diced",
      "1 green bell pepper, diced",
      "1 onion, chopped",
      "2 cloves garlic, minced",
      "1/2 cup pineapple chunks, fresh or canned",
      "3 tbsp ketchup",
      "1 tbsp soy sauce",
      "1 tbsp rice vinegar",
      "2 tbsp brown sugar",
      "1/2 tsp salt",
      "1/4 cup water",
      "1 tbsp sesame seeds (for garnish)",
      "1 cup Jasmine rice",
    ],
    recipe: [
      "Wrap the tofu in a clean towel and place a heavy object on top to press out excess water for about 20 minutes. Then, cut the tofu into cubes.",
      "Toss the tofu cubes with cornstarch to coat evenly.",
      "Heat vegetable oil in a pan over medium heat, add the tofu cubes, and fry until golden and crispy. Remove from the pan and set aside.",
      "In the same pan, add garlic, onion, and bell peppers and sauté until slightly tender.",
      "Add pineapple chunks to the pan and cook for another 2 minutes.",
      "In a bowl, mix ketchup, soy sauce, rice vinegar, brown sugar, salt, and water to create the sweet and sour sauce.",
      "Pour the sauce into the pan with the vegetables and pineapple, bringing it to a simmer.",
      "Return the crispy tofu to the pan, toss to coat in the sauce, and heat through.",
      "Garnish with sesame seeds.",
      "Serve the sweet and sour tofu hot over steamed Jasmine rice.",
    ],
    image_key: "dish/Sweet_and_Sour_Tofu.png",
    youtube_link: [
      "PfH4Bvvdl_o",
      "Mnc-U_DqYoM",
      "BFT0whFD4JM",
      "57W9joGL3Ew",
      "7Vzd9qQC5kU",
    ],
    created_at: "2024-10-17T08:59:22.672000",
  },
  {
    dish_name: "Sweet Paneer Tikka",
    dish_description:
      "A delightful vegetarian Punjabi dish made from paneer, marinated in sweetened yogurt and spices, then grilled to perfection.",
    ingredients: [
      "200g paneer, cut into cubes",
      "1 cup thick yogurt",
      "2 tablespoons honey",
      "1 tablespoon ginger-garlic paste",
      "1 teaspoon garam masala",
      "1 teaspoon chaat masala",
      "1/2 teaspoon red chili powder",
      "Salt to taste",
      "1 tablespoon oil",
      "Diced vegetables (bell peppers, onions, tomatoes) for skewering",
    ],
    recipe: [
      "In a bowl, mix the yogurt, honey, ginger-garlic paste, garam masala, chaat masala, red chili powder, and salt together.",
      "Add the paneer cubes to the marinade and gently mix, ensuring the paneer is well-coated. Let it marinate for at least 1 hour.",
      "Preheat your grill to medium-high heat.",
      "Skewer the marinated paneer and diced vegetables alternately on skewers.",
      "Brush the grill with oil and place the skewers on the grill.",
      "Grill the skewers, turning occasionally, until the paneer is golden and vegetables are cooked, about 10-15 minutes.",
      "Serve hot, garnished with cilantro or a drizzle of lime juice if desired.",
    ],
    image_key: "dish/Sweet_Paneer_Tikka.png",
    youtube_link: [
      "33dUzc-7Myk",
      "c-oVDb-O2Q8",
      "Nru8aadeN0I",
      "U1LVDFwi8qI",
      "kZxmErE7V2E",
    ],
    created_at: "2024-10-17T09:01:09.055000",
  },
  {
    dish_name: "Rajasthani Gatte Ki Sabzi",
    dish_description:
      "A traditional Rajasthani vegetarian dish consisting of spicy gram flour (besan) dumplings in a rich yoghurt-based curry.",
    ingredients: [
      "1 cup gram flour (besan)",
      "1/4 cup curd (yogurt)",
      "2 tbsp cooking oil",
      "1/4 tsp asafoetida (hing)",
      "1/2 tsp cumin seeds",
      "1/2 tsp mustard seeds",
      "2 green chilies, finely chopped",
      "1 tsp ginger paste",
      "1 tsp garlic paste",
      "1/2 tsp turmeric powder",
      "1 tsp red chili powder",
      "1 tsp coriander powder",
      "1 tsp garam masala",
      "1/2 cup tomato puree",
      "4 cups water",
      "Salt to taste",
      "Handful of coriander leaves, chopped",
    ],
    recipe: [
      "In a bowl, mix gram flour, 1/2 tsp salt, 1/2 tsp chili powder, 1/4 tsp turmeric powder, 1 tbsp oil, and 1/4 cup curd to form a stiff dough.",
      "Divide the dough into small portions and roll each into a log shape. Boil water in a saucepan, add the dough logs, and cook for about 10 minutes. Drain and cut into small pieces once cooled.",
      "Heat oil in a pan. Add cumin seeds, mustard seeds, and asafoetida. Once they start to crackle, add chopped green chilies, ginger paste, and garlic paste.",
      "Add the remaining turmeric, chili powder, coriander powder, garam masala, and salt to taste. Stir well.",
      "Add tomato puree and cook until oil starts to separate from the masala.",
      "Add the yogurt, water, and bring the mixture to a boil. Then add the cooked gatte (dumplings) and simmer for 10 minutes.",
      "Garnish with chopped coriander leaves and serve hot with rice or roti.",
    ],
    image_key: "dish/Rajasthani_Gatte_Ki_Sabzi.png",
    youtube_link: [
      "mVwjjnwAIXY",
      "4_rBh5AomG0",
      "orN-iPAgOMM",
      "Sy2WXE0v1dI",
      "E-AqIiHFL48",
    ],
    created_at: "2024-10-17T09:02:27.641000",
  },
  {
    dish_name: "Spicy Butter Chicken",
    dish_description:
      "A rich and creamy Punjabi dish combining succulent pieces of chicken in a spicy, buttery, tomato-based sauce, enhanced with a touch of cream.",
    ingredients: [
      "500 grams of boneless chicken, cut into cubes",
      "200 grams of unsalted butter",
      "1 cup of heavy cream",
      "3 large onions, finely chopped",
      "4 tomatoes, pureed",
      "6 cloves of garlic, minced",
      "1 inch piece of ginger, minced",
      "2 green chillies, finely chopped",
      "1 teaspoon of cumin seeds",
      "1 teaspoon of turmeric powder",
      "2 teaspoons of garam masala",
      "1 teaspoon of red chili powder",
      "Salt to taste",
      "Fresh cilantro for garnish",
      "2 tablespoons of vegetable oil",
      "1 cup of water",
    ],
    recipe: [
      "Heat oil in a large skillet and add cumin seeds until they start to crackle.",
      "Add the chopped onions to the skillet and sauté until they are golden brown.",
      "Mix in the minced ginger, garlic, and green chillies, cooking for a few minutes until fragrant.",
      "Stir the tomato puree into the skillet and cook for about 10 minutes until the oil begins to separate.",
      "Add turmeric, chili powder, and half the garam masala. Mix well.",
      "Place the chicken pieces into the skillet, coat them with the mixture, and cook for 10 minutes.",
      "Pour in water, bring to a boil, then simmer for 15 minutes or until the chicken is tender.",
      "Incorporate butter and cream into the skillet, stirring continuously until butter melts and integrates into the sauce.",
      "Sprinkle the remaining garam masala and salt to taste. Allow to simmer for another 5 minutes.",
      "Garnish with fresh cilantro before serving.",
    ],
    image_key: "dish/Spicy_Butter_Chicken.png",
    youtube_link: [
      "a03U45jFxOI",
      "6tMUbWjEWiY",
      "913xQZBG1yE",
      "3r-r1Eprl18",
      "ho-M0Z4aQTU",
    ],
    created_at: "2024-10-17T09:02:44.675000",
  },
  {
    dish_name: "Laal Maas",
    dish_description:
      "Laal Maas is a fiery Rajasthani vegetarian curry made with marinated tofu as a substitute for meat, simmered in a spicy and rich gravy of tomatoes, onions, and traditional Indian spices.",
    ingredients: [
      "500 grams tofu, cubed",
      "3 tablespoons mustard oil",
      "2 large onions, finely chopped",
      "4 cloves garlic, minced",
      "1-inch ginger, minced",
      "4 large tomatoes, pureed",
      "2 green chilies, slit",
      "1/2 cup yogurt, whisked",
      "1 teaspoon cumin seeds",
      "2 bay leaves",
      "1 cinnamon stick",
      "2 cardamoms",
      "1 teaspoon turmeric powder",
      "2 teaspoons coriander powder",
      "3 teaspoons red chili powder",
      "1 teaspoon garam masala",
      "Salt to taste",
      "Fresh cilantro for garnish",
    ],
    recipe: [
      "Heat mustard oil in a large pot until it reaches its smoking point. Then reduce the heat to medium.",
      "Add cumin seeds, bay leaves, cinnamon, and cardamom. Sauté until they start to crackle.",
      "Add chopped onions and sauté until they become golden brown.",
      "Add minced garlic and ginger, sauté for another 2 minutes until fragrant.",
      "Stir in turmeric, coriander, and red chili powder, and cook for a minute till the spices release their aromas.",
      "Add pureed tomatoes and slit green chilies, and cook on medium heat till the oil separates from the gravy.",
      "Season with salt, and mix in the cubed tofu, ensuring the pieces are well coated with the masala.",
      "Reduce heat and slowly add the whisked yogurt to the gravy, stirring continuously to prevent the yogurt from curdling.",
      "Cover and let it simmer for about 10-15 minutes, or until the tofu is cooked through and the gravy is thick.",
      "Sprinkle garam masala over the curry and mix well.",
      "Garnish with fresh cilantro before serving.",
      "Serve hot with rice or Indian breads like roti or naan.",
    ],
    image_key: "dish/Laal_Maas.png",
    youtube_link: [
      "xAhZZiZ5S50",
      "c-g0SyQd6Fk",
      "x6VBBUDXQbo",
      "bG2nwUSWezg",
      "AivEzaOwKKw",
    ],
    created_at: "2025-03-08T11:04:36.036000",
  },
  {
    dish_name: "Masala Dosa",
    dish_description:
      "A crispy, savory South Indian fermented crepe made from rice batter and black lentils, filled with spicy mashed potatoes.",
    ingredients: [
      "1 cup urad dal (split black lentils)",
      "3 cups rice",
      "Salt to taste",
      "Water as needed for batter",
      "2 large potatoes, boiled and mashed",
      "2 tablespoons oil",
      "1 teaspoon mustard seeds",
      "1/2 teaspoon turmeric powder",
      "2 green chilies, finely chopped",
      "1 onion, finely chopped",
      "Salt to taste",
      "Curry leaves (optional)",
      "2 tablespoons chopped coriander leaves",
    ],
    recipe: [
      "Wash and soak the urad dal and rice separately for at least 6 hours.",
      "Grind the urad dal and rice to a fine paste, adding water gradually to form a smooth batter.",
      "Mix the ground dal and rice, add salt, and allow to ferment overnight.",
      "For the masala, heat oil in a pan. Add mustard seeds and let them splutter.",
      "Add chopped onions, green chilies, and curry leaves. Sauté until onions are golden brown.",
      "Add turmeric powder and salt to the mashed potatoes, mix well.",
      "Add this potato mixture to the sautéed onions and mix well. Cook for a few minutes, then add chopped coriander leaves.",
      "Heat a non-stick pan and pour a ladleful of batter, spreading it evenly to form a thin circle.",
      "Drizzle a little oil around the edges and cook until the dosa turns golden brown.",
      "Place some potato masala on one half of the dosa, fold it, and serve hot with coconut chutney and sambar.",
    ],
    image_key: "dish/Masala_Dosa.png",
    youtube_link: [
      "J75VQSxOtdo",
      "sX5pYdNbmgo",
      "UiS8UBEe8FI",
      "gY1LXg8AnU4",
      "XgGH3K4agNY",
    ],
    created_at: "2024-10-17T09:03:45.546000",
  },
  {
    dish_name: "Butter Chicken",
    dish_description:
      "Butter chicken is a rich and flavorful curry dish originating from the Punjab region. It consists of tender chicken pieces marinated in spices and yogurt, cooked in a creamy tomato sauce infused with butter and cream.",
    ingredients: [
      "500 grams chicken, boneless",
      "1 cup yogurt",
      "1 tablespoon lemon juice",
      "2 teaspoons turmeric powder",
      "2 teaspoons garam masala",
      "2 teaspoons red chili powder",
      "2 tablespoons ginger garlic paste",
      "Salt to taste",
      "3 tablespoons butter",
      "1 large onion, finely chopped",
      "1 cup tomato puree",
      "1/2 cup cream",
      "1 tablespoon sugar",
      "1 teaspoon crushed fenugreek leaves",
      "Fresh cilantro for garnish",
    ],
    recipe: [
      "Clean and cut the chicken into bite-sized pieces.",
      "In a bowl, mix yogurt, lemon juice, 1 teaspoon turmeric, 1 teaspoon garam masala, 1 teaspoon red chili powder, ginger garlic paste, and salt. Add chicken to the marinade and let it rest for at least 1 hour.",
      "Heat 1 tablespoon butter in a large pan or skillet. Add the marinated chicken and cook until all sides are golden brown. Set aside.",
      "In the same pan, add 2 tablespoons of butter. Saute the chopped onions until they turn translucent.",
      "Add tomato puree, remaining turmeric, garam masala, and red chili powder. Cook for about 5 minutes until the oil starts separating from the tomato mixture.",
      "Add the cooked chicken back to the pan. Mix well so that the chicken is coated with the tomato mixture.",
      "Add cream, sugar, and crushed fenugreek leaves. Simmer on low heat for about 10 minutes or until the chicken is cooked thoroughly.",
      "Garnish with fresh cilantro and serve hot with naan or rice.",
    ],
    image_key: "dish/Butter_Chicken.png",
    youtube_link: [
      "a03U45jFxOI",
      "6tMUbWjEWiY",
      "913xQZBG1yE",
      "ho-M0Z4aQTU",
      "Z8iqYIANHS8",
    ],
    created_at: "2024-10-17T09:09:33.328000",
  },
  {
    dish_name: "Spicy Vegan Undhiyu",
    dish_description:
      "A traditional Gujarati vegetable casserole, Undhiyu is a delightful mix of winter vegetables and spices, prepared in an earthen pot. This spicy vegan version captures the essence of Gujarat with a fiery twist.",
    ingredients: [
      "100g surti papdi (string beans), trimmed",
      "50g purple yam, peeled and chopped",
      "50g sweet potatoes, peeled and chopped",
      "50g small eggplants, slit",
      "2 ripe bananas, peeled and halved",
      "100g firm tofu, cubed",
      "2 tbsp green peas",
      "1 cup coconut milk",
      "2 tbsp sesame seeds",
      "1 tbsp grated ginger",
      "2 green chilies, finely chopped",
      "1 tsp cumin seeds",
      "1/2 tsp turmeric powder",
      "1 tsp coriander powder",
      "1 tsp garam masala",
      "2 tbsp groundnut oil",
      "Salt to taste",
      "Fresh coriander for garnish",
    ],
    recipe: [
      "In a bowl, mix coconut milk with sesame seeds, ginger, green chilies, cumin seeds, turmeric powder, coriander powder, and salt to prepare the masala.",
      "Heat the oil in a heavy-bottomed pan. Add the garam masala and let it sizzle.",
      "Add all the vegetables and tofu to the pan and stir well to coat with the spices.",
      "Pour in the prepared masala mix and stir everything together gently.",
      "Cover and cook on a low flame for about 20 minutes or until the vegetables are tender.",
      "Uncover, increase the heat to medium, and cook for another 10 minutes to allow the sauce to thicken slightly.",
      "Check seasoning and adjust salt if necessary.",
      "Garnish with fresh coriander before serving.",
      "Serve hot with freshly made rotis or as a standalone dish.",
    ],
    image_key: "dish/Spicy_Vegan_Undhiyu.png",
    youtube_link: [
      "OFTWBaVC_gw",
      "76WP69qtDi8",
      "HgH5UD53Rc8",
      "UcBwSYSqlVc",
      "N_5Fh5anoig",
    ],
    created_at: "2024-10-17T09:25:07.851000",
  },
  {
    dish_name: "Vegetarian Chinese Congee",
    dish_description:
      "A comforting and warm rice porridge commonly eaten for breakfast, infused with the flavors of fresh ginger, scallions, and a hint of sesame.",
    ingredients: [
      "1 cup jasmine rice",
      "8 cups water",
      "2 tablespoons soy sauce",
      "1 inch fresh ginger, grated",
      "1/4 cup chopped scallions",
      "1 tablespoon sesame oil",
      "Salt to taste",
      "Optional toppings: sliced tofu, steamed bok choy, roasted peanuts",
    ],
    recipe: [
      "Rinse the jasmine rice thoroughly under cold water until the water runs clear.",
      "In a large pot, combine the rinsed rice and 8 cups of water. Bring to a boil over high heat.",
      "Reduce heat to low and simmer, covered, for about 1 to 1.5 hours. Stir occasionally to prevent the rice from sticking to the bottom.",
      "Once the rice has broken down into a creamy porridge, stir in the soy sauce, grated ginger, and sesame oil. Season with salt to taste.",
      "Simmer for an additional 10 minutes to allow the flavors to meld together.",
      "Serve the congee hot in bowls, garnished with chopped scallions and any additional toppings of your choice.",
    ],
    image_key: "dish/Vegetarian_Chinese_Congee.png",
    youtube_link: [
      "t2SahnNVULA",
      "SrnBalc6m5w",
      "0a18tgMBEZc",
      "MgDGFWXGTC0",
      "VcqfFYhHT-o",
    ],
    created_at: "2024-10-17T09:25:20.409000",
  },
  {
    dish_name: "Vegan Sev Tameta Nu Shaak",
    dish_description:
      "A traditional Gujarati dish, Sev Tameta Nu Shaak is a spicy, tangy, and slightly sweet curry made with tomatoes and topped with crispy chickpea flour noodles known as sev. This vegan version captures the essence of Gujarati flavors.",
    ingredients: [
      "2 tablespoons vegetable oil",
      "1 teaspoon mustard seeds",
      "1 teaspoon cumin seeds",
      "A pinch of asafoetida (hing) - optional",
      "6 medium tomatoes, finely chopped",
      "1 tablespoon ginger-garlic paste",
      "2 green chillies, slit",
      "1/2 teaspoon turmeric powder",
      "1 teaspoon red chilli powder",
      "1 teaspoon coriander powder",
      "1/2 teaspoon garam masala",
      "Salt to taste",
      "1 teaspoon sugar",
      "2 cups vegan sev",
      "Fresh coriander leaves for garnish",
    ],
    recipe: [
      "Heat the oil in a pan. Add mustard seeds and cumin seeds. Allow them to splutter.",
      "Add a pinch of asafoetida, if using.",
      "Add finely chopped tomatoes along with ginger-garlic paste and slit green chillies. Cook until the tomatoes are soft and mushy.",
      "Stir in turmeric powder, red chilli powder, coriander powder, garam masala, salt, and sugar. Mix well and cook for another 5-7 minutes on medium flame.",
      "Once the curry is cooked and oil begins to separate from the sides, remove from heat.",
      "Just before serving, add the vegan sev and mix well.",
      "Garnish with fresh coriander leaves.",
      "Serve hot with rotis or as a side dish with rice.",
    ],
    image_key: "dish/Vegan_Sev_Tameta_Nu_Shaak.png",
    youtube_link: [
      "DHj-ndtkKJw",
      "s2PuzbKU3Ds",
      "NoiI-P4ugr8",
      "WAHoETx7qYk",
      "Xl8KX5QZS1Q",
    ],
    created_at: "2024-10-17T09:25:42.130000",
  },
  {
    dish_name: "Honey Glazed Chicken with Sesame",
    dish_description:
      "Tender chicken pieces glazed in a sweet honey sauce, garnished with sesame seeds to bring a crunchy texture, this dish is a delicious blend of sweetness and savory flavors of Chinese cuisine.",
    ingredients: [
      "500g chicken breast, cut into cubes",
      "2 tablespoons vegetable oil",
      "1 large onion, sliced",
      "2 cloves garlic, minced",
      "1 green bell pepper, cut into pieces",
      "4 tablespoons honey",
      "2 tablespoons soy sauce",
      "1 tablespoon rice vinegar",
      "1 teaspoon fresh ginger, grated",
      "1 teaspoon cornstarch dissolved in 1 tablespoon water",
      "Salt to taste",
      "Black pepper to taste",
      "1 tablespoon sesame seeds",
      "Spring onions, sliced, for garnish",
    ],
    recipe: [
      "Heat the oil in a large pan over medium heat. Add the chicken cubes and fry until golden brown and cooked through.",
      "Remove the chicken from the pan and set aside.",
      "In the same pan, add a little more oil if needed, then add the onion, garlic, and green bell pepper. Sauté until the onions are translucent.",
      "Return the chicken to the pan. Add the honey, soy sauce, rice vinegar, and grated ginger. Stir well to combine all the ingredients.",
      "Allow the sauce to simmer for a few minutes until it starts to thicken. Then add the dissolved cornstarch to the pan and stir well. Cook for another 2-3 minutes or until the sauce has thickened.",
      "Season with salt and black pepper to taste.",
      "Sprinkle sesame seeds over the chicken just before serving.",
      "Garnish with spring onions and serve hot with steamed rice or noodles.",
    ],
    image_key: "dish/Honey_Glazed_Chicken_with_Sesame.png",
    youtube_link: [
      "TJ9yBpqTHns",
      "xAqqkaNlmIg",
      "cO-DjvowmQ8",
      "2kHgZIav0tU",
      "hfxledIyK6I",
    ],
    created_at: "2024-10-17T09:27:12.940000",
  },
  {
    dish_name: "Laal Maas",
    dish_description:
      "Laal Maas is a traditional Rajasthani non-vegetarian dish noted for its fiery hot flavor and aromatic spices. It has a deep red color due to the liberal use of chili peppers.",
    ingredients: [
      "500 grams of mutton, cut into pieces",
      "2 cups of water",
      "1 cup of yogurt",
      "2 tablespoons of garlic paste",
      "2 tablespoons of ginger paste",
      "5 tablespoons mustard oil",
      "10-15 dried red chillies, soaked in water",
      "1 teaspoon cumin seeds",
      "3-4 cardamom pods",
      "2 bay leaves",
      "1 cinnamon stick",
      "4 cloves",
      "200 grams of onions, finely chopped",
      "Salt to taste",
      "Chopped coriander for garnish",
    ],
    recipe: [
      "Heat the mustard oil in a large pot until it starts to smoke. Then reduce the heat to medium.",
      "Add cumin seeds, cardamom, bay leaves, cinnamon stick, and cloves. Sauté for a few seconds until aromatic.",
      "Add chopped onions and cook until they turn golden.",
      "Blend the soaked red chillies into a smooth paste and add it to the pot, fry till the oil separates.",
      "Add ginger and garlic paste. Sauté for 2-3 minutes until the raw smell dissipates.",
      "Add the mutton pieces to the pot. Brown the meat on all sides.",
      "Beat the yogurt and then pour it over the mutton. Stir well to coat the meat.",
      "Add water and salt. Bring the mixture to a boil, then cover and simmer over low heat for about 60-90 minutes until the mutton is tender.",
      "Adjust the seasoning if necessary.",
      "Garnish with chopped coriander before serving.",
      "Serve hot with naan or rice.",
    ],
    image_key: "dish/Laal_Maas.png",
    youtube_link: [
      "xAhZZiZ5S50",
      "x6VBBUDXQbo",
      "c-g0SyQd6Fk",
      "_V6W6gdqrnE",
      "bG2nwUSWezg",
    ],
    created_at: "2024-10-17T09:27:11.426000",
  },
  {
    dish_name: "Gatte Ki Sabzi",
    dish_description:
      "A traditional Rajasthani vegetarian dish made from gram flour (besan) dumplings, cooked in a tangy yogurt-based curry. This savory curry is a staple in Rajasthani cuisine and is known for its unique flavors.",
    ingredients: [
      "1 cup gram flour (besan)",
      "1/4 tsp baking soda",
      "1 tsp red chili powder",
      "1 tsp turmeric powder",
      "1 tsp coriander seeds, crushed",
      "2 tbsp oil",
      "Salt to taste",
      "1 cup yogurt, whisked",
      "2 tbsp ghee",
      "1 tsp cumin seeds",
      "1 pinch asafoetida",
      "1 onion, finely chopped",
      "2 tomatoes, pureed",
      "1 tsp ginger-garlic paste",
      "2 green chilies, slit",
      "1/2 tsp garam masala",
      "Fresh coriander leaves, chopped for garnishing",
      "Water as required",
    ],
    recipe: [
      "In a bowl, mix gram flour, baking soda, 1/2 tsp red chili powder, 1/2 tsp turmeric powder, crushed coriander seeds, salt, and 1 tbsp oil. Add water gradually to make a stiff dough.",
      "Divide the dough into equal portions and roll each portion into a cylindrical shape.",
      "Boil water in a large pot and cook the rolled dough cylinders for about 10 minutes or until they float to the top. Drain and let them cool.",
      "Cut the boiled cylinders into small bite-sized pieces, called 'Gatte'.",
      "Heat ghee in a pan, add cumin seeds and asafoetida. Once the seeds crackle, add chopped onions and sauté until golden brown.",
      "Add ginger-garlic paste, green chilies, and cook for another minute.",
      "Stir in the pureed tomatoes, remaining red chili powder, and turmeric powder. Cook until oil separates from the masala.",
      "Lower the heat and slowly add whisked yogurt to the pan, stirring continuously to avoid curdling.",
      "Add about 1 cup of water and bring the curry to a boil.",
      "Add the Gatte pieces to the curry and let it simmer for about 10 minutes, allowing the Gatte to absorb the flavors.",
      "Finish with garam masala and simmer for another minute.",
      "Garnish with fresh coriander leaves before serving.",
      "Serve warm with roti or rice.",
    ],
    image_key: "dish/Gatte_Ki_Sabzi.png",
    youtube_link: [
      "mVwjjnwAIXY",
      "rOp4cKdsbQw",
      "lbNnFX5WvL4",
      "4_rBh5AomG0",
      "TSMl7STQdH0",
    ],
    created_at: "2024-10-17T09:27:13.522000",
  },
  {
    dish_name: "Ker Sangri",
    dish_description:
      "Ker Sangri is a traditional Rajasthani dish made with wild berries (ker) and desert beans (sangri), cooked with an array of local spices. This vegetarian delicacy is often enjoyed in arid regions and features a tangy and spicy flavor profile.",
    ingredients: [
      "50g ker (dried desert berries)",
      "50g sangri (dried desert beans)",
      "3 tablespoons oil",
      "1 teaspoon cumin seeds",
      "1/2 teaspoon asafoetida (hing)",
      "1 teaspoon turmeric powder",
      "2 teaspoons coriander powder",
      "1 teaspoon red chili powder",
      "Salt to taste",
      "2 tablespoons amchur (dry mango powder)",
      "2 tablespoons chopped fresh coriander for garnish",
    ],
    recipe: [
      "Soak the ker and sangri in water overnight to rehydrate them.",
      "Drain the water and rinse the ker and sangri thoroughly.",
      "Heat oil in a pan and add the cumin seeds and asafoetida.",
      "Once the seeds start to crackle, add the turmeric powder, coriander powder, and red chili powder. Stir well.",
      "Add the soaked ker and sangri to the pan and mix well to coat with the spices.",
      "Season with salt and cook on medium-low heat for about 10 minutes or until the beans are tender.",
      "Stir in the amchur powder and cook for an additional 5 minutes.",
      "Garnish with chopped fresh coriander before serving.",
      "Serve hot with rotis or as a side dish with your main meal.",
    ],
    image_key: "dish/Ker_Sangri.png",
    youtube_link: [
      "T7oERZawp4o",
      "farM50c1fbc",
      "__jR9LYN0aM",
      "P_H_5mX80IE",
      "hAh2pZnHBio",
    ],
    created_at: "2024-10-17T15:05:35.686000",
  },
  {
    dish_name: "Huevos Rancheros with Chorizo",
    dish_description:
      "A spicy and hearty Mexican breakfast dish featuring eggs on corn tortillas with chorizo sausage and spicy tomato-chili sauce.",
    ingredients: [
      "4 corn tortillas",
      "4 large eggs",
      "100 grams chorizo sausage, crumbled",
      "1 cup canned tomatoes, diced",
      "1 small onion, diced",
      "2 cloves garlic, minced",
      "1 jalapeno, seeded and minced",
      "1/2 teaspoon cumin powder",
      "1/4 teaspoon chili powder",
      "1/2 teaspoon salt",
      "1/4 cup fresh cilantro, chopped",
      "1 avocado, sliced",
      "1/4 cup queso fresco, crumbled",
      "2 tablespoons vegetable oil",
    ],
    recipe: [
      "Heat one tablespoon of vegetable oil in a pan over medium heat. Add the chorizo and cook until browned. Remove the chorizo from the pan and set aside.",
      "In the same pan, add the onion, garlic, and jalapeno, cooking until they are soft and fragrant.",
      "Stir in the cumin, chili powder, salt, and diced tomatoes. Allow to simmer for about 10 minutes until the sauce thickens slightly.",
      "In another pan, heat the remaining oil and gently fry the corn tortillas one at a time, keeping them warm.",
      "Fry each egg in the remaining oil to your preferred doneness.",
      "To assemble, place a warm tortilla on each plate, top each with a fried egg, spoonfuls of the tomato-chili sauce, chorizo, slices of avocado, and sprinkle with queso fresco and chopped cilantro.",
    ],
    image_key: "dish/Huevos_Rancheros_with_Chorizo.png",
    youtube_link: [
      "uLlM8o7YxhY",
      "7khus9sla3c",
      "Zn1wf6lF49s",
      "xL3dQHepQxo",
      "WiVSn84tlqs",
    ],
    created_at: "2024-10-23T04:39:45.715000",
  },
  {
    dish_name: "Spicy Pyaaz Ki Kachori",
    dish_description:
      "A popular spicy breakfast snack from Rajasthan, Pyaaz ki Kachori is a type of deep-fried pastry filled with a delicious onion mixture flavored with a variety of spices.",
    ingredients: [
      "2 cups all-purpose flour",
      "1/4 cup melted ghee",
      "Salt to taste",
      "Water as needed",
      "2 tablespoons oil",
      "1 teaspoon cumin seeds",
      "1/2 teaspoon fennel seeds",
      "2 cups finely chopped onions",
      "1 teaspoon ginger paste",
      "1 teaspoon green chili paste",
      "2 tablespoons gram flour",
      "1 teaspoon coriander powder",
      "1 teaspoon garam masala",
      "1/2 teaspoon red chili powder",
      "1 teaspoon dried mango powder",
      "2 tablespoons finely chopped coriander leaves",
      "Oil for deep frying",
    ],
    recipe: [
      "In a bowl, mix all-purpose flour, melted ghee, and salt. Add water gradually and knead into a stiff dough. Cover and let it rest for 30 minutes.",
      "Heat oil in a pan. Add cumin seeds and fennel seeds, allow them to splutter.",
      "Add chopped onions and sauté until they turn slightly golden.",
      "Add ginger paste, green chili paste, and sauté for a minute.",
      "Sprinkle gram flour over the onions and cook for 2-3 minutes or until the raw smell disappears.",
      "Add coriander powder, garam masala, red chili powder, dried mango powder and mix well. Cook for another 2 minutes.",
      "Turn off the heat and add chopped coriander leaves. Allow the mixture to cool.",
      "Divide the dough into equal portions, roll each into a ball. Flatten each ball slightly and place a portion of the onion filling in the center.",
      "Seal the edges and shape them into a ball again. Flatten it slightly to form the kachoris.",
      "Heat oil in a deep pan and deep fry the kachoris over medium heat until golden brown.",
      "Drain on paper towels to remove excess oil.",
      "Serve hot with tamarind or green chutney.",
    ],
    image_key: "dish/Spicy_Pyaaz_Ki_Kachori.png",
    youtube_link: [
      "PBqK0kEx4-c",
      "OnU2I8uO1mQ",
      "urY8nTA_aoQ",
      "MeVJC5iP_nU",
      "5AAC5IHy72U",
    ],
    created_at: "2024-10-30T18:23:48.019000",
  },
  {
    dish_name: "Rajasthani Mirchi Vada",
    dish_description:
      "Rajasthani Mirchi Vada is a popular spicy street food from Rajasthan which consists of large green chilies stuffed with a tangy potato filling, coated in a gram flour batter and deep-fried until golden. It is often served with mint or tamarind chutney.",
    ingredients: [
      "8 large green chilies (bhavnagri or mild jalapenos)",
      "3 large potatoes, boiled and mashed",
      "1 tsp cumin seeds",
      "1/2 tsp turmeric powder",
      "1 tsp coriander powder",
      "1/2 tsp garam masala",
      "1/2 tsp amchur (dry mango powder)",
      "Salt to taste",
      "2 cups gram flour (besan)",
      "1 tsp red chili powder",
      "Water as needed",
      "Oil for deep frying",
    ],
    recipe: [
      "Slit each chili lengthwise and remove the seeds carefully to prepare for stuffing.",
      "In a bowl, mix mashed potatoes with cumin seeds, turmeric powder, coriander powder, garam masala, amchur, and salt.",
      "Stuff the chilies with the seasoned potato mixture.",
      "Prepare the batter by mixing gram flour, red chili powder, and salt. Add water gradually to form a thick batter.",
      "Heat oil in a deep frying pan.",
      "Dip the stuffed chilies into the batter, ensuring they are well coated.",
      "Deep fry the chilies in hot oil until they are golden brown and crispy.",
      "Drain on paper towels to remove excess oil.",
      "Serve hot with mint chutney or tamarind chutney.",
    ],
    image_key: "dish/Rajasthani_Mirchi_Vada.png",
    youtube_link: [
      "5oSulCW3QGw",
      "fLnt1tu_nQg",
      "o9dmzl3NMGM",
      "RNULyVl1laU",
      "QnkwFx4kvq4",
    ],
    created_at: "2024-11-27T06:59:29.432000",
  },
  {
    dish_name: "Spicy Masala Dosa",
    dish_description:
      "Masala Dosa is a popular South Indian breakfast dish consisting of a crispy crepe made from fermented rice and lentil batter, filled with a spicy potato filling.",
    ingredients: [
      "1 cup of rice",
      "1/2 cup of urad dal (split black lentils)",
      "Salt to taste",
      "Water as needed for batter",
      "2 tbsp oil",
      "1 tsp mustard seeds",
      "1 tsp turmeric powder",
      "2 green chilies, finely chopped",
      "1 onion, finely chopped",
      "5-6 curry leaves",
      "500 grams potatoes, boiled and mashed",
      "2 tbsp chopped cilantro",
      "Oil or ghee for cooking dosas",
    ],
    recipe: [
      "Soak the rice and urad dal in water in separate bowls for 6-8 hours.",
      "Drain the water and grind both the rice and urad dal together in a blender to make a fine paste. Add enough water to form a batter.",
      "Add salt to the batter and let it ferment overnight.",
      "Prepare the filling: Heat oil in a pan, add mustard seeds, and let them splutter.",
      "Add chopped onions and green chilies, and fry until the onions turn translucent.",
      "Add turmeric powder and curry leaves, and sauté for a few seconds.",
      "Add the mashed potatoes and mix well. Check for salt and adjust as per taste.",
      "Add chopped cilantro and mix again.",
      "Heat a non-stick pan and lightly grease it with oil or ghee. Pour a ladle of batter and spread it evenly by lifting and rotating the pan.",
      "Once the edges start lifting, spread a teaspoon of oil or ghee around the edges, and place some potato filling in the center.",
      "Fold the dosa over the filling to make a semi-circle or a roll.",
      "Serve hot with coconut chutney and sambar.",
    ],
    image_key: "dish/Spicy_Masala_Dosa.png",
    youtube_link: [
      "sX5pYdNbmgo",
      "soAjw44q8tY",
      "gY1LXg8AnU4",
      "IDNtiYTd7_M",
      "UiS8UBEe8FI",
    ],
    created_at: "2025-02-15T05:00:02.558000",
  },
  {
    dish_name: "Classic Eggs Benedict with Smoked Salmon",
    dish_description:
      "Eggs Benedict, a timeless breakfast dish that combines the luxurious flavors of smoked salmon and a rich, creamy hollandaise sauce over perfectly poached eggs and toasted English muffins.",
    ingredients: [
      "4 English muffins, halved",
      "8 slices of smoked salmon",
      "8 eggs",
      "2 tablespoons white vinegar",
      "200 grams unsalted butter",
      "3 egg yolks",
      "1 tablespoon lemon juice",
      "1/2 teaspoon salt",
      "1/4 teaspoon cayenne pepper",
      "Fresh dill for garnish",
      "Black pepper to taste",
    ],
    recipe: [
      "Split and toast the English muffins until golden brown.",
      "Bring a large saucepan of water to a simmer. Add the white vinegar.",
      "Crack each egg into a small cup and gently pour into the simmering water. Poach the eggs for about 3-4 minutes until the whites are set but yolks remain runny. Remove with a slotted spoon and drain on a warm plate.",
      "For the hollandaise sauce, melt the butter in a small pot. Place egg yolys in a blender, and while blending at medium speed, gradually add melted butter until the sauce thickens. Blend in lemon juice, salt, and cayenne pepper.",
      "Place two halves of the English muffins on each plate. Top each half with a slice of smoked salmon, followed by a poached egg.",
      "Pour the hollandaise sauce generously over the eggs and garnish with fresh dill and a sprinkle of black pepper.",
      "Serve immediately.",
    ],
    image_key: "dish/Classic_Eggs_Benedict_with_Smoked_Salmon.png",
    youtube_link: [
      "_-23DXcFTuQ",
      "c8T_gtzHa5g",
      "YeDZWA0drwQ",
      "Woiiet4vQ58",
      "vv6XFIq1pXA",
    ],
    created_at: "2025-02-15T05:04:07.395000",
  },
  {
    dish_name: "Spicy Methi Thepla",
    dish_description:
      "A traditional Gujarati flatbread made with fenugreek leaves, whole wheat flour, and spices, offering a spicy and flavorful start to the day.",
    ingredients: [
      "2 cups whole wheat flour",
      "1 cup fresh fenugreek leaves (methi), finely chopped",
      "2 green chilies, finely chopped",
      "1 inch ginger, grated",
      "1/2 teaspoon turmeric powder",
      "1/2 teaspoon red chili powder",
      "1/2 teaspoon cumin seeds",
      "1/2 teaspoon coriander powder",
      "Salt to taste",
      "2 tablespoons yogurt",
      "2 tablespoons oil",
      "Water as needed for kneading",
      "Additional oil for cooking",
    ],
    recipe: [
      "In a large bowl, mix whole wheat flour, chopped fenugreek leaves, green chilies, and ginger.",
      "Add turmeric powder, red chili powder, cumin seeds, coriander powder, and salt to the mixture.",
      "Mix in the yogurt and oil to the flour mixture and start to knead, adding water gradually until the dough is soft and pliable.",
      "Cover the dough and let it rest for at least 30 minutes.",
      "Divide the dough into small balls. Roll each ball into a thin circle using a rolling pin, dusting with flour as needed to prevent sticking.",
      "Heat a tava or skillet on medium heat. Place the rolled thepla on the tava and cook until small bubbles appear on the surface. Brush with oil and flip. Cook until both sides have golden brown spots.",
      "Serve hot with a side of yogurt or pickle for a spicy breakfast treat.",
    ],
    image_key: "dish/Spicy_Methi_Thepla.png",
    youtube_link: [
      "A2C9CY8ZymQ",
      "nBPIVZ5ivig",
      "zcUiTqcGUM4",
      "mFTfjVOQEkI",
      "C8MVLf0DBc8",
    ],
    created_at: "2025-02-15T05:07:17.939000",
  },
  {
    dish_name: "Rajasthani Mirchi Vada with Sweet Tamarind Chutney",
    dish_description:
      "A traditional spicy Rajasthani snack, Mirchi Vada is made from big green chilies stuffed with a spicy potato filling, coated in chickpea flour and deep fried, served with a sweet tamarind chutney.",
    ingredients: [
      "6 large green chilies",
      "2 large potatoes, boiled and mashed",
      "1 tsp cumin seeds",
      "1 tsp garam masala",
      "1/2 tsp amchur (dry mango powder)",
      "Salt to taste",
      "2 cups chickpea flour (besan)",
      "1 tsp red chili powder",
      "Water as needed for batter",
      "Oil for deep frying",
      "1 cup tamarind pulp",
      "1/2 cup jaggery, grated",
      "1 tsp roasted cumin powder",
      "1/2 tsp red chili powder",
      "1/2 tsp ginger powder",
      "Salt to taste",
    ],
    recipe: [
      "For the stuffing, mix the mashed potatoes with cumin seeds, garam masala, amchur, and salt.",
      "Slit each chili vertically, de-seed, and stuff with the potato mixture.",
      "Prepare a smooth batter using chickpea flour, red chili powder, salt, and water.",
      "Heat oil in a deep pan.",
      "Dip each stuffed chili into the batter, ensuring it is well coated, and deep fry until golden brown.",
      "For the chutney, in a saucepan, combine tamarind pulp, jaggery, red chili powder, cumin powder, ginger powder, and salt. Cook over low heat until the mixture thickens.",
      "Serve hot Mirchi Vadas with sweet tamarind chutney on the side.",
    ],
    image_key: "dish/Rajasthani_Mirchi_Vada_with_Sweet_Tamarind_Chutney.png",
    youtube_link: [
      "rYWN3uFpAg4",
      "Su5jW7E-v9Y",
      "0Uv8Biy0IKU",
      "KOMfBHnABbQ",
      "fLnt1tu_nQg",
    ],
    created_at: "2025-02-26T04:42:42.155000",
  },
  {
    dish_name: "Ker Sangri",
    dish_description:
      "Ker Sangri is a traditional Rajasthani dish made with dried berries (Ker) and beans (Sangri). It is a spicy and tangy veg dish, representing the desert cuisine of Rajasthan.",
    ingredients: [
      "50g dried Ker (desert berries)",
      "100g Sangri (dried desert beans)",
      "2 tbsp oil",
      "1/4 tsp asafoetida (hing)",
      "1 tsp mustard seeds",
      "2 tsp fennel seeds",
      "2 tbsp coriander powder",
      "1 tsp turmeric powder",
      "2 tsp red chili powder",
      "1 tsp dried mango powder (amchur)",
      "Salt to taste",
      "2 tbsp fresh cilantro, chopped for garnishing",
    ],
    recipe: [
      "Soak the Ker and Sangri in water overnight to rehydrate them.",
      "Drain the water and rinse the Ker and Sangri thoroughly to remove any dirt or debris.",
      "Heat oil in a pan over medium heat and add mustard seeds. Allow them to crackle.",
      "Add asafoetida, fennel seeds, and sauté for a few seconds.",
      "Add the rehydrated Ker and Sangri to the pan. Stir well.",
      "Add coriander powder, turmeric, chili powder, and salt. Mix well to coat the Ker and Sangri evenly with the spices.",
      "Reduce the heat to low and cook covered for about 10-15 minutes, stirring occasionally, until the ingredients are cooked and have absorbed the flavors.",
      "Stir in the dried mango powder and cook for another 2 minutes.",
      "Garnish with fresh cilantro before serving.",
      "Serve hot with chapatis or steamed rice.",
    ],
    image_key: "dish/Ker_Sangri.png",
    youtube_link: [
      "T7oERZawp4o",
      "farM50c1fbc",
      "wFjhR9rDpvQ",
      "P_H_5mX80IE",
      "__jR9LYN0aM",
    ],
    created_at: "2025-03-05T05:06:57.422000",
  },
  {
    dish_name: "Spicy Szechuan Paneer Dosa",
    dish_description:
      "A unique fusion dish blending the heat and flavors of Szechuan cuisine with the traditional South Indian dosa, using paneer as a protein-packed vegetarian ingredient.",
    ingredients: [
      "1 cup dosa batter",
      "200 grams paneer, cut into cubes",
      "2 tablespoons Szechuan sauce",
      "1 onion, finely chopped",
      "1 bell pepper, finely chopped",
      "2 green chilies, finely chopped",
      "1 tablespoon ginger-garlic paste",
      "2 tablespoons oil",
      "Salt to taste",
      "Chopped spring onions for garnish",
    ],
    recipe: [
      "Heat 1 tablespoon of oil in a pan and add the ginger-garlic paste, green chilies, and onion. Sauté until the onions turn translucent.",
      "Add the bell pepper and paneer cubes to the pan. Fry until the paneer is light golden.",
      "Pour in the Szechuan sauce and mix well. Cook for an additional 2-3 minutes, then set aside.",
      "Heat a non-stick pan and pour a ladleful of dosa batter, spreading it into a thin circle.",
      "Drizzle a little oil around the edges and cook on medium heat until the dosa is crispy.",
      "Place a portion of the Szechuan paneer mixture on one half of the dosa and fold it over.",
      "Serve hot, garnished with chopped spring onions.",
    ],
    image_key: "dish/Spicy_Szechuan_Paneer_Dosa.png",
    youtube_link: [
      "-8CBXZaYwJc",
      "BbqDlylrQKA",
      "tNrPso0T9Yo",
      "6vI0wbhVFbo",
      "0sfMjSA29YE",
    ],
    created_at: "2025-03-11T11:25:19.978000",
  },
  {
    dish_name: "Pyaaz Kachori",
    dish_description:
      "Pyaaz Kachori is a popular breakfast dish from Rajasthan. It's a deep-fried pastry filled with a spicy onion mixture, seasoned with a variety of spices that provide a rich and satisfying flavor suitable for a spicy breakfast.",
    ingredients: [
      "2 cups all-purpose flour",
      "1/4 cup melted ghee",
      "Water as needed",
      "Oil for deep frying",
      "2 large onions, finely chopped",
      "1 tablespoon ginger paste",
      "1 tablespoon garlic paste",
      "2 green chilies, chopped",
      "1 teaspoon fennel seeds",
      "1 teaspoon coriander seeds, crushed",
      "1/2 teaspoon turmeric powder",
      "1 teaspoon red chili powder",
      "1 teaspoon garam masala",
      "Salt to taste",
      "2 tablespoons fresh coriander leaves, chopped",
      "1 tablespoon amchur (dry mango powder)",
    ],
    recipe: [
      "In a large mixing bowl, combine flour and melted ghee. Add water gradually and knead into a stiff dough. Cover and set aside to rest.",
      "Heat oil in a pan and add fennel seeds and crushed coriander seeds. Stir until they start to splutter.",
      "Add chopped onions, ginger paste, garlic paste, and chopped green chilies to the pan. Fry until onions turn golden brown.",
      "Add turmeric powder, red chili powder, garam masala, and salt. Mix well and cook for another few minutes.",
      "Stir in amchur and fresh coriander leaves, then remove from heat and let the mixture cool.",
      "Divide the dough into equal portions and roll each into a ball. Flatten each ball and place a portion of the onion mixture in the center. Seal the edges and flatten to form a kachori shape.",
      "Heat oil in a deep frying pan. Deep fry the kachoris on medium heat until golden brown and crispy.",
      "Drain on absorbent paper and serve hot.",
    ],
    image_key: "dish/Pyaaz_Kachori.png",
    youtube_link: [
      "5AAC5IHy72U",
      "PBqK0kEx4-c",
      "urY8nTA_aoQ",
      "MeVJC5iP_nU",
      "USMiMjZtwVY",
    ],
    created_at: "2025-03-13T22:11:10.639000",
  },
  {
    dish_name: "Sarson Ka Saag",
    dish_description:
      "A traditional Punjabi dish made from mustard greens and spices, perfect for a spicy and hearty vegan dinner.",
    ingredients: [
      "500g mustard greens, finely chopped",
      "200g spinach, finely chopped",
      "2 medium onions, finely chopped",
      "4 cloves garlic, minced",
      "2 inches ginger, minced",
      "2 green chilies, finely chopped",
      "1 tsp garam masala",
      "1 tsp turmeric powder",
      "1 tsp red chili powder",
      "2 tbsp cornmeal",
      "Salt to taste",
      "4 tbsp mustard oil",
    ],
    recipe: [
      "In a large pot, heat the mustard oil over medium heat.",
      "Add the onions, garlic, ginger, and green chilies. Sauté until the onions are translucent.",
      "Add the mustard greens and spinach, stir well to combine with the aromatics.",
      "Add the turmeric powder, red chili powder, and salt. Mix thoroughly.",
      "Cover the pot and let the greens cook on a medium-low heat for about 30 minutes, or until they are completely wilted and tender.",
      "Add cornmeal to the mixture. This helps in thickening the saag slightly and adds texture.",
      "Cook for another 10 minutes, stirring occasionally.",
      "Turn off the heat and stir in the garam masala.",
      "For an extra touch of flavor, you can consider a tadka (tempering) of mustard seeds in hot oil poured over the dish.",
      "Serve hot with chapati or makki di roti.",
    ],
    image_key: "dish/Sarson_Ka_Saag.png",
    youtube_link: [
      "UOjl3X3-qD0",
      "fU5G92KqnLo",
      "tdjHs1SvZ-w",
      "Re17lSewdy8",
      "HBf-GBZwvU4",
    ],
    created_at: "2025-03-17T15:11:36.872000",
  },
  {
    dish_name: "Masala Poha",
    dish_description:
      "A spicy and savory traditional Gujarati breakfast dish made with flattened rice seasoned with mustard seeds, green chilies, and turmeric, garnished with fresh coriander and grated coconut.",
    ingredients: [
      "2 cups flattened rice (poha)",
      "2 tbsp oil",
      "1 tsp mustard seeds",
      "8-10 curry leaves",
      "2 green chilies, finely chopped",
      "1/2 cup finely chopped onions",
      "1/2 tsp turmeric powder",
      "Salt to taste",
      "1 tsp sugar",
      "2 tbsp lemon juice",
      "1/4 cup fresh coriander, chopped",
      "2 tbsp grated coconut",
      "2 tbsp roasted peanuts",
      "Optional: pomegranate seeds for garnish",
    ],
    recipe: [
      "Rinse the flattened rice in a colander until water runs clear. Leave it to drain completely.",
      "Heat oil in a pan and add the mustard seeds. When they start to splutter, add curry leaves and chopped green chilies. Saute for a few seconds.",
      "Add the chopped onions and saute until they turn translucent.",
      "Sprinkle turmeric powder and stir well.",
      "Add the drained poha and mix gently to coat the rice with the turmeric-oil mixture. Season with salt and sugar.",
      "Cover and cook for 2-3 minutes on low heat to allow the flavors to blend.",
      "Switch off the heat. Drizzle lemon juice over the poha and mix gently.",
      "Garnish with chopped coriander, grated coconut, roasted peanuts, and optionally, pomegranate seeds.",
      "Serve hot and enjoy a flavorful Gujarati breakfast!",
    ],
    image_key: "dish/Masala_Poha.png",
    youtube_link: [
      "7alwAoCg0pc",
      "hL-BnQF_gmI",
      "UXaOuBoatUA",
      "8LwYrE7PaC0",
      "PD3U6nTBChk",
    ],
    created_at: "2025-03-19T08:59:11.419000",
  },
  {
    dish_name: "Ghevar with Sweet Rabri",
    dish_description:
      "Ghevar is a traditional Rajasthani sweet dish typically prepared during festivals. It's a disc-shaped sweet cake made with all-purpose flour and soaked in sugar syrup. This version is served with sweet rabri, adding a creamy, flavorful topping.",
    ingredients: [
      "1 cup all-purpose flour",
      "2 tbsp ghee (clarified butter)",
      "200 ml water",
      "1/2 cup milk",
      "1 pinch saffron",
      "Ghee for frying",
      "For sugar syrup:",
      "1 cup sugar",
      "1 cup water",
      "Cardamom powder (a pinch)",
      "For Rabri:",
      "1 liter full-fat milk",
      "1/4 cup sugar",
      "Saffron strands (a few)",
      "Chopped nuts (almonds, pistachios) for garnish",
      "Dried rose petals (optional for garnish)",
    ],
    recipe: [
      "Make the batter for Ghevar: Mix all-purpose flour, ghee, and water to form a runny batter.",
      "Heat ghee in a deep pan. Pour a ladleful of batter in the center of the pan in a thin stream. Allow it to spread on its own.",
      "Fry till edges turn golden brown, then remove carefully and drain excess ghee.",
      "Prepare sugar syrup by boiling sugar and water until one-string consistency. Add cardamom powder and mix well.",
      "Dip the fried Ghevar in sugar syrup and remove after a minute. Allow to cool.",
      "Prepare Rabri: Boil milk in a heavy-bottomed pan. Reduce the milk to half its volume by simmering and stir in sugar and saffron.",
      "Pour thick rabri over cooled Ghevar.",
      "Garnish with chopped nuts and optionally, dried rose petals before serving.",
    ],
    image_key: "dish/Ghevar_with_Sweet_Rabri.png",
    youtube_link: [
      "zIKIw4lkSoM",
      "Bh87si4LpLI",
      "boSEp96t93M",
      "4q1_Min37N0",
      "2B1w_Ndhcjk",
    ],
    created_at: "2025-03-19T09:04:04.461000",
  },
  {
    dish_name: "Mirchi Vada",
    dish_description:
      "Mirchi Vada, also known as Jodhpuri Mirchi Bada, is a popular spicy street food from Rajasthan. It consists of large green chili peppers stuffed with spicy potato filling, coated in a chickpea flour batter, and deep-fried until golden.",
    ingredients: [
      "8 large green chili peppers (mild)",
      "4 medium potatoes, boiled and mashed",
      "1 teaspoon cumin seeds",
      "1 teaspoon fennel seeds",
      "1/2 teaspoon turmeric powder",
      "1 teaspoon coriander powder",
      "1 teaspoon garam masala",
      "1 tablespoon ginger, finely chopped",
      "2 tablespoons coriander leaves, chopped",
      "Salt to taste",
      "1 cup chickpea flour (besan)",
      "1/4 teaspoon baking soda",
      "1/2 teaspoon red chili powder",
      "Water as needed",
      "Oil for frying",
    ],
    recipe: [
      "Slit the green chilies from the middle and deseed them. Rinse and pat dry.",
      "In a bowl, mix mashed potatoes with cumin seeds, fennel seeds, turmeric, coriander powder, garam masala, ginger, coriander leaves, and salt.",
      "Stuff each chili with the potato mixture.",
      "Prepare the batter by combining chickpea flour, baking soda, red chili powder, and salt. Add water gradually to make a smooth, thick batter.",
      "Heat oil in a deep frying pan.",
      "Dip each stuffed chili in the batter to coat evenly and deep fry until golden brown.",
      "Drain on paper towels to remove excess oil.",
      "Serve hot with mint chutney or tamarind sauce.",
    ],
    image_key: "dish/Mirchi_Vada.png",
    youtube_link: [
      "5oSulCW3QGw",
      "o9dmzl3NMGM",
      "QnkwFx4kvq4",
      "fLnt1tu_nQg",
      "gzH29VPskY0",
    ],
    created_at: "2025-05-05T12:13:59.462000",
  },
  {
    dish_name: "Spicy Besan Cheela",
    dish_description:
      "Spicy Besan Cheela is a popular Rajasthani breakfast dish made from gram flour. This easy-to-make savory pancake is enhanced with spicy green chilies and carom seeds, offering a delicious and nutritious start to the day.",
    ingredients: [
      "1 cup gram flour (besan)",
      "2 finely chopped green chilies",
      "1/2 tsp carom seeds (ajwain)",
      "1/4 tsp turmeric powder",
      "Salt to taste",
      "Water as needed to make a batter",
      "2 tbsp chopped coriander leaves",
      "Oil for cooking",
    ],
    recipe: [
      "In a large mixing bowl, combine the gram flour, chopped green chilies, carom seeds, turmeric powder, and salt.",
      "Gradually add water to the mixture and whisk continuously to form a lump-free batter with a consistency similar to pancake batter.",
      "Stir in the chopped coriander leaves into the batter.",
      "Heat a non-stick pan over medium heat and lightly grease it with oil.",
      "Pour a ladleful of batter onto the hot pan and spread it evenly to form a thin circle.",
      "Cook on medium heat until the edges start to lift from the pan and the bottom is golden brown.",
      "Flip the cheela and cook the other side for about 2 minutes, or until golden and crisp.",
      "Remove from the pan and serve hot with your choice of chutney or yogurt.",
    ],
    image_key: "dish/Spicy_Besan_Cheela.png",
    youtube_link: [
      "kFHJ0T-LKY0",
      "QROJTp9011s",
      "9-lR8Kv7aOk",
      "7iHGzA-IL-E",
      "lxRR5-gpKz4",
    ],
    created_at: "2025-05-05T12:16:48.259000",
  },
  {
    dish_name: "Upma with a Spicy Twist",
    dish_description:
      "Upma, a traditional South Indian breakfast dish made from semolina, is a staple that is both nourishing and hearty. This version adds a spicy twist, appealing to those who prefer a zesty kick to start their day.",
    ingredients: [
      "1 cup semolina (rava)",
      "1 large onion, finely chopped",
      "2 green chilies, finely chopped",
      "1 tsp mustard seeds",
      "1 tsp cumin seeds",
      "1/2 tsp asafoetida (hing)",
      "1 sprig curry leaves",
      "2 tbsp vegetable oil",
      "2 1/2 cups water",
      "Salt to taste",
      "1/2 tsp red chili powder",
      "1/2 cup fresh coriander, chopped",
      "1 tbsp lemon juice",
    ],
    recipe: [
      "Heat oil in a pan over medium heat. Add mustard seeds and cumin seeds and let them splutter.",
      "Add chopped onions and green chilies, sauté until onions are translucent.",
      "Sprinkle asafoetida and curry leaves into the pan, stir for a few seconds.",
      "Add semolina (rava) to the pan. Roast the semolina for about 5 minutes on medium heat, stirring continuously to avoid lumps until it turns light golden.",
      "Pour water into the pan, add salt and red chili powder. Increase heat to high and bring the mixture to a boil.",
      "Reduce the heat to low, cover the pan, and allow the upma to cook for about 5-7 minutes, or until all the water is absorbed.",
      "Remove from heat. Add chopped coriander and lemon juice, mix well.",
      "Serve hot. Garnish with additional coriander if desired.",
    ],
    image_key: "dish/Upma_with_a_Spicy_Twist.png",
    youtube_link: [
      "5sL6f0goWok",
      "B7e7XNLKFLo",
      "y_zMRV0DqXo",
      "CAwwBYZe2Jc",
      "idPUCRX2sNA",
    ],
    created_at: "2025-05-07T06:34:45.657000",
  },
  {
    dish_name: "Ghevar",
    dish_description:
      "Ghevar is a traditional Rajasthani sweet dish, typically enjoyed during festivals. It is a disc-shaped dessert made from flour, ghee, and sugar syrup, with a delightful crunch and sweetness.",
    ingredients: [
      "3 cups all-purpose flour",
      "1/2 cup ghee (clarified butter)",
      "4 cups water",
      "2 cups sugar",
      "1/3 cup milk, full cream",
      "Ice cubes",
      "1 teaspoon lemon juice",
      "Saffron strands for garnishing",
      "Sliced almonds and pistachios for garnishing",
      "Edible silver leaf (optional)",
    ],
    recipe: [
      "In a large mixing bowl, mix ghee and ice-cold water with some ice cubes until it becomes frothy.",
      "Gradually add flour to the ghee and water mixture to form a smooth, runny batter.",
      "Heat ghee in a deep pan or kadhai. Pour a ladleful of batter in the center of the kadhai in a steady stream. The batter should settle into a disc or web-like form.",
      "Fry the Ghevar on medium heat until it turns golden and crisp. Remove and drain excess ghee.",
      "Prepare sugar syrup by boiling water, sugar, and lemon juice until it reaches a one-thread consistency.",
      "Dip the fried Ghevar in sugar syrup and let it soak for a few minutes. Remove and let the excess syrup drain.",
      "Garnish with saffron, sliced almonds, pistachios, and edible silver leaf before serving.",
    ],
    image_key: "dish/Ghevar.png",
    youtube_link: [
      "Bh87si4LpLI",
      "E8evYzyItVM",
      "yocNN4fDJNQ",
      "X5tdJ2OGWrA",
      "zIKIw4lkSoM",
    ],
    created_at: "2025-05-07T11:54:08.149000",
  },
  {
    dish_name: "Ghewar",
    dish_description:
      "Ghewar is a traditional Rajasthani sweet delicately prepared from milk, ghee, and flour, known for its disc-like shape and unique honeycomb texture. It is especially popular during festivals.",
    ingredients: [
      "1 cup all-purpose flour",
      "1/4 cup ghee",
      "1/4 cup ice-cold water",
      "2 cups sugar",
      "1 cup water (for sugar syrup)",
      "1 tsp cardamom powder",
      "2 tbsp milk",
      "1/2 tsp lemon juice",
      "Ghee for deep frying",
      "Saffron strands for garnishing",
      "Sliced almonds and pistachios for garnishing",
    ],
    recipe: [
      "Prepare a syrup by dissolving sugar in 1 cup of water and boiling until it reaches one-string consistency. Add cardamom powder and lemon juice to prevent crystallization.",
      "Mix flour and ghee in a bowl. Gradually add ice-cold water and mix to form a smooth batter similar to pancake batter consistency.",
      "Heat ghee in a deep pan for frying. Pour a ladleful of batter in the center of the pan and allow it to spread. Cook on medium heat until the edges turn golden.",
      "Carefully remove the ghewar with a skewer and drain excess ghee.",
      "Dip the cooked ghewar into the warm sugar syrup for a few seconds, then remove and let excess syrup drip off.",
      "Garnish with saffron, sliced almonds, and pistachios before serving.",
    ],
    image_key: "dish/Ghewar.png",
    youtube_link: [
      "Bh87si4LpLI",
      "zIKIw4lkSoM",
      "E8evYzyItVM",
      "A-me4fPdtCE",
      "4q1_Min37N0",
    ],
    created_at: "2025-05-19T14:09:35.097000",
  },
  {
    dish_name: "Churma Ladoo",
    dish_description:
      "A traditional Rajasthani sweet, Churma Ladoo is made from coarse whole-wheat flour balls deep fried in ghee and sweetened with jaggery or sugar. It's a delightful treat often served during special occasions.",
    ingredients: [
      "2 cups whole wheat flour",
      "1/2 cup semolina (sooji)",
      "1/2 cup melted ghee, plus extra for deep frying",
      "3/4 cup powdered jaggery",
      "1/2 teaspoon cardamom powder",
      "1/4 cup mixed nuts (almonds, cashews), chopped",
      "Water as needed to knead dough",
    ],
    recipe: [
      "In a mixing bowl, combine the whole wheat flour, semolina, and 1/4 cup of ghee. Mix well.",
      "Slowly add water and knead into a stiff dough.",
      "Divide the dough into small portions and shape them into round balls.",
      "Heat the ghee in a deep frying pan and deep fry the dough balls on low heat until golden brown. Remove and let them cool.",
      "Once cooled, crush the fried balls into a fine mixture using a food processor or mortar and pestle.",
      "In a pan, heat the remaining ghee, add the powdered jaggery, and stir until it melts completely.",
      "Add the crushed dough mixture to the melted jaggery along with cardamom powder and the chopped nuts. Mix well until everything is well combined.",
      "While the mixture is still warm, shape it into round ladoos with your palms.",
      "Let the Churma Ladoos cool completely before serving.",
    ],
    image_key: "dish/Churma_Ladoo.png",
    youtube_link: [
      "6gTR49i0Y48",
      "L8Dp6EfMMT4",
      "387f0iW3Jzw",
      "lroDfiCV0YM",
      "mH01ReYZQ7o",
    ],
    created_at: "2025-06-05T09:40:19.696000",
  },
  {
    dish_name: "Eggs Benedict",
    dish_description:
      "A classic American breakfast dish that consists of English muffins topped with smoked ham, poached eggs, and rich hollandaise sauce.",
    ingredients: [
      "2 English muffins, halved",
      "4 slices of smoked ham",
      "4 large eggs",
      "2 teaspoons white vinegar",
      "1 cup unsalted butter",
      "3 egg yolks",
      "1 tablespoon lemon juice",
      "1 pinch cayenne pepper",
      "Salt to taste",
    ],
    recipe: [
      "Split the English muffins in half and toast them until they are lightly browned.",
      "Place slices of smoked ham on each half of the muffins and set aside.",
      "To poach the eggs: Fill a pot with about 3 inches of water, add vinegar, and bring to a slight simmer. Crack each egg into a small cup, then gently pour the eggs one by one into the simmering water. Poach the eggs for 3-4 minutes, then remove with a slotted spoon.",
      "For the hollandaise sauce: Melt butter in a saucepan. In a separate bowl, whisk together egg yolks, lemon juice, and cayenne pepper. Slowly whisk in the melted butter until the mixture thickens and doubles in volume.",
      "Assemble the Eggs Benedict by placing a poached egg on top of each ham-covered muffin half. Pour hollandaise sauce over the eggs.",
      "Garnish with a pinch of salt and serve warm.",
    ],
    image_key: "dish/Eggs_Benedict.png",
    youtube_link: [
      "c8T_gtzHa5g",
      "gBJjRYk0yC0",
      "v7BQf_t7oOw",
      "-WmoBVQafJE",
      "NEhmNhrYp78",
    ],
    created_at: "2025-06-12T16:29:58.329000",
  },
  {
    dish_name: "Laal Maas",
    dish_description:
      "Laal Maas is a popular Rajasthani non-vegetarian dish known for its fiery spicy taste. It is made with mutton cooked in a sauce of yogurt and hot spices such as red chilies. This dish is traditionally cooked with a smoky flavor, giving it a unique aromatic essence suitable for a hearty lunch.",
    ingredients: [
      "500g mutton, cut into pieces",
      "2 cups yogurt",
      "3 tbsp mustard oil",
      "10-12 dried red chilies",
      "1 tbsp garlic paste",
      "1 tbsp ginger paste",
      "2 large onions, finely chopped",
      "1 tsp cumin seeds",
      "4 cloves",
      "2 bay leaves",
      "1 cinnamon stick",
      "1 tsp turmeric powder",
      "Salt to taste",
      "Fresh coriander for garnish",
      "Water as needed",
    ],
    recipe: [
      "Heat the mustard oil in a large heavy-bottomed pan until it begins to smoke slightly.",
      "Add the cumin seeds, cloves, bay leaves, and cinnamon stick to sauté until they start to crackle.",
      "Add the chopped onions and fry until they turn golden brown.",
      "Stir in the garlic paste and ginger paste, and cook for a couple more minutes until fragrant.",
      "Put the mutton pieces into the pan and fry on high heat until they are evenly browned on all sides.",
      "Lower the heat and add the yogurt, turmeric powder, and dried red chilies, mixing thoroughly.",
      "Season with salt, and add enough water to cover the mutton. Bring to a boil.",
      "Cover and simmer on low heat until the mutton is tender and the oil begins to separate from the gravy.",
      "Adjust the consistency and seasoning as needed.",
      "Garnish with fresh coriander and serve hot with rice or Indian bread.",
    ],
    image_key: "dish/Laal_Maas.png",
    youtube_link: [
      "xAhZZiZ5S50",
      "c-g0SyQd6Fk",
      "x6VBBUDXQbo",
      "bG2nwUSWezg",
      "GckLnitE0xk",
    ],
    created_at: "2025-07-20T12:38:42.459000",
  },
  {
    dish_name: "Sweet and Sour Chicken",
    dish_description:
      "A delightful breakfast version of the classic Chinese sweet and sour chicken, featuring crispy fried chicken pieces coated in a sweet and tangy sauce.",
    ingredients: [
      "200g chicken breast, cut into bite-sized pieces",
      "1/2 cup cornstarch",
      "1 egg, beaten",
      "Salt to taste",
      "Oil for frying",
      "1/2 red bell pepper, chopped",
      "1/2 green bell pepper, chopped",
      "1/2 cup pineapple chunks",
      "1 spring onion, chopped",
      "For the sauce:",
      "1/4 cup sugar",
      "2 tablespoons ketchup",
      "1/4 cup white vinegar",
      "1 tablespoon soy sauce",
      "1 teaspoon garlic paste",
    ],
    recipe: [
      "Season the chicken pieces with salt and coat them in the beaten egg.",
      "Place the cornstarch in a separate bowl and dredge the egg-coated chicken pieces until fully covered.",
      "Heat the oil in a frying pan and fry the chicken pieces until golden brown and crispy. Remove and set aside.",
      "In the same pan, sauté red and green bell peppers and spring onions until just soft.",
      "To make the sauce, mix together sugar, ketchup, vinegar, soy sauce, and garlic paste in a bowl until smooth.",
      "Add the sauce mixture to the pan with the vegetables and bring to a simmer.",
      "Add the fried chicken pieces and pineapple chunks to the pan. Stir well, ensuring the chicken is coated with the sauce.",
      "Cook for another 2-3 minutes until everything is heated through and the sauce has thickened slightly.",
      "Serve hot, garnished with additional chopped spring onions if desired.",
    ],
    image_key: "dish/Sweet_and_Sour_Chicken.png",
    youtube_link: [
      "cblsP5S9PhU",
      "KL6t2eMrT5A",
      "hK2r9KsWlKk",
      "O7oAbHXi38o",
      "3LtcGWOBmUo",
    ],
    created_at: "2025-07-23T18:34:10.292000",
  },
];
